### ISSUE TITLE
Nesting with postcss-nesting instead of postcss-nested fails

### ISSUE THREAD

**Issue by AlecRust** [GarthDB/postcss-inherit#164]
Given this source CSS:

```css
.u-hiddenVisually {
  border: 0 !important;
  clip: rect(1px, 1px, 1px, 1px) !important;
  height: 1px !important;
  overflow: hidden !important;
  padding: 0 !important;
  position: absolute !important;
  width: 1px !important;
}

/* then later in a different file: */

.FormField--hiddenLabel {

  & .FormField-label {

    @inherit: .u-hiddenVisually;
  }
}
```

I would expect this output:

```css
.u-hiddenVisually,
.FormField--hiddenLabel .FormField-label {
  border: 0 !important;
  clip: rect(1px, 1px, 1px, 1px) !important;
  height: 1px !important;
  overflow: hidden !important;
  padding: 0 !important;
  position: absolute !important;
  width: 1px !important;
}
```

But instead I get this output:

```css
.u-hiddenVisually,
& .FormField-label {
  border: 0 !important;
  clip: rect(1px, 1px, 1px, 1px) !important;
  height: 1px !important;
  overflow: hidden !important;
  padding: 0 !important;
  position: absolute !important;
  width: 1px !important;
}
```

This occurs when I switch from `postcss-nested` to `postcss-nesting`. I'm not sure if it's an issue with `postcss-inherit` or `postcss-nesting`.
