### ISSUE TITLE
keyframes get lost

### ISSUE THREAD

**Issue by selfrefactor** [GarthDB/postcss-inherit#36]
I have the following issue when using animation keyframes such as:
```css
@keyframes fontbulger {
    0% {
        font-size: 10px;
    }
    30% {
        font-size: 15px;
    }
    100% {
        font-size: 12px;
    }
}

#box {
    animation: fontbulger 2s infinite;
}
```

as this plugin turns the above code to:

```css
#box {
    animation: 2s infinite;
}
```
