### ISSUE TITLE
Fix Media Disjoint

### ISSUE THREAD

**Issue by GarthDB** [GarthDB/postcss-inherit#6]
It is failing the `media.disjoint.css` test.

It is returning:

``` css
@media (min-width: 320px) {
  .button1 {
    color: gray;
  }
}
```

When it should be:

``` css
@media (min-width: 320px) {
  .button1,
  .button2 {
    color: gray;
  }
}
```
